# ================================================
# Microsoft Stock Price Analysis Using R
# ================================================
# Author: Richard Frimpong
# Date: 15th January 2025
# Purpose: Perform data preprocessing, exploratory data analysis (EDA), and 
#          build predictive models for Microsoft stock price forecasting using R.
# ================================================

# =============================
# Step 1: Loading Required Libraries
# =============================
# Load necessary libraries for data manipulation, visualization, and modeling
library(tidyverse)     # For data manipulation and visualization
library(lubridate)     # For working with dates
library(caret)         # For model training and evaluation
library(randomForest)  # For Random Forest model
library(ggplot2)       # For enhanced visualization
library(ggcorrplot)    # For correlation visualizations
library(gridExtra)     # For arranging multiple plots
library(forecast)      # For Time Series Analysis
library(zoo)           # Ensure this is included for moving averages


# =============================
# Step 2: Load and Inspect Data
# =============================

# Set Working Directory
setwd("C:\\Personal Documents\\University of Sheffield, MSc Data Science\\INF6027 Introduction to Data Science (AUTUMN 2024~25)")


# Load the dataset (Ensure the file path is correct)
msft_data <- read.csv("msft.csv")


# Display the first few rows of the dataset to understand its structure
head(msft_data)
# Check the structure of the dataset (data types and column names)
str(msft_data)


# =============================
# Step 3: Data Preprocessing
# =============================
# Convert the 'Date' column to a Date format using lubridate
# Convert 'Date' column to Date format (ensure no errors with inconsistent date formats)
msft_data$Date <- dmy(msft_data$Date)

# Check the structure of the data to confirm date conversion
str(msft_data)


# ==========================================================

# Step 4: Feature Engineering (Create New Features)
# ==========================================================
# Extract Year, Month, and Day of Week for temporal analysis

msft_data$Year <- year(msft_data$Date)
msft_data$Month <- month(msft_data$Date)
msft_data$DayOfWeek <- wday(msft_data$Date, label = TRUE)

# Calculate daily returns as percentage change in closing price
msft_data$DailyReturn <- c(NA, diff(msft_data$Close) / head(msft_data$Close, -1) * 100)

# Calculate short-term (10-day) and long-term (50-day) simple moving averages
msft_data$SMA_10 <- zoo::rollmean(msft_data$Close, 10, fill = NA, align = "right")
msft_data$SMA_50 <- zoo::rollmean(msft_data$Close, 50, fill = NA, align = "right")

# =============================
# Step 5: Handling Missing Values
# =============================
# Check for missing values in the dataset
sum(is.na(msft_data))  # Total number of missing values in the dataset
# NOTE: 59 missing values were identified in the dataset
# Check the first 5 rows of the dataset
head(msft_data) 

# chech columns with missing values
colSums(is.na(msft_data)) 

# Remove rows with missing values (NA) generated by moving averages and returns
msft_data <- na.omit(msft_data)

# Check the processed data
head(msft_data)

# =============================
# Step 6: Exploratory Data Analysis (EDA)
# =============================
# Visualize Time Series of Microsoft’s Closing Price
# Plot the closing price of Microsoft over time
# High Quality Visualization
ggplot(msft_data, aes(x = Date, y = Close)) +
  geom_line(color = "blue") +
  labs(title = "Microsoft Stock Closing Price Over Time", 
       subtitle = "Time Series Plot of Microsoft Stock Closing Price", 
       caption = "Data source: Stock Market Data (NASDAQ, NYSE, S&P500)-MSFT") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, color = "darkblue", size = 14, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, color = "darkblue", size = 12),
        plot.caption = element_text(hjust = 1, size = 10, face = "italic"),
        plot.background = element_rect(fill = "lightgray", color = "white"),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "lightblue", linewidth = 0.5),  # Changed size to linewidth
        panel.grid.minor = element_line(color = "lightblue", linewidth = 0.25),  # Changed size to linewidth
        axis.title = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 10, color = "black"),
        axis.ticks = element_line(color = "gray")) +
  xlab("Date") + ylab("Closing Price (USD)")




# 3.2 Correlation Heatmap of Financial Indicators
# Compute correlation matrix
correlation_matrix <- cor(msft_data[, c("Low", "Open", "Volume", "High", "Close", "Adjusted.Close", "SMA_10", "SMA_50", "DailyReturn")], use = "complete.obs")

# Generate the correlation heatmap
heatmap_plot <- ggcorrplot(correlation_matrix, 
                           hc.order = TRUE, 
                           type = "lower", 
                           lab = TRUE, 
                           lab_size = 3, # Adjust label size for readability
                           method = "square", # Using square blocks for a more uniform presentation
                           colors = c("#0066FF", "#FFFFFF", "#FF3300"), # Professional blue-white-red color scheme
                           title = "Correlation Heatmap of Microsoft Stock Features", 
                           ggtheme = theme_minimal(base_size = 16)) # High-quality theme

# Add high-quality background and fine-tune the plot
heatmap_plot + 
  theme(
    plot.title = element_text(hjust = 0.5, color = "#1A1A1A", size = 14, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, color = "#666666", size = 14),
    plot.caption = element_text(hjust = 1, size = 10, face = "italic", color = "#888888"),
    plot.background = element_rect(fill = "#F4F4F4", color = NA),  # Professional light background
    panel.background = element_rect(fill = "white"),
    panel.grid = element_blank(),  # Remove grid for a clean look
    axis.text = element_text(size = 12, color = "#333333"),
    axis.title = element_text(size = 14, face = "bold", color = "#333333"),
    axis.ticks = element_line(color = "#D1D1D1"),
    legend.position = "bottom",
    legend.title = element_text(face = "bold", color = "#333333"),
    legend.text = element_text(color = "#333333")
  ) +
  labs(caption = "Data source: Stock Market Data (NASDAQ, NYSE, S&P500)-MSFT")



# =============================
# Step 7: Model Development
# ============================
# Data Splitting
# Split the data into training (80%) and testing (20%) datasets
set.seed(42)  # Ensure reproducibility
train_index <- createDataPartition(msft_data$Close, p = 0.8, list = FALSE)
train_data <- msft_data[train_index, ]
test_data <- msft_data[-train_index, ]

# Check the split data sizes
dim(train_data)
dim(test_data)

# The output of the dim() function indicates the sizes of your training and testing datasets:

# Training Data (train_data): 7375 rows (observations) and 13 columns (features/variables).

#Testing Data (test_data): 1840 rows (observations) and 13 columns (features/variables).



# =============================
# Step 8: Building the Random Forest Model
# =============================
# Train the Random Forest model
rf_model <- randomForest(Close ~ Low + Open + Volume + High + SMA_10 + SMA_50 + DailyReturn, 
                         data = train_data, 
                         ntree = 500, 
                         mtry = 3, 
                         importance = TRUE)

# Print the model summary
print(rf_model)

# =============================
# Step 9: Feature Importance
# =============================
# Visualize feature importance
# Convert importance data to a data frame
importance_df <- as.data.frame(importance(rf_model))
importance_df$Feature <- rownames(importance_df)

# Plot %IncMSE
ggplot(importance_df, aes(x = reorder(Feature, `%IncMSE`), y = `%IncMSE`)) +
  geom_bar(stat = "identity", fill = "#6EC1E4", color = "#4A92B4", size = 0.5) +
  coord_flip() +
  labs(title = "Feature Importance (%IncMSE)",
       x = "Features", y = "% Increase in MSE",
       caption = "Data source: Stock Market Data (NASDAQ, NYSE, S&P500)-MSFT") +
  theme_minimal(base_size = 14) +
  theme(plot.title = element_text(hjust = 0.5, color = "#1A1A1A", size = 16, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, color = "#4D4D4D", size = 14),
        plot.caption = element_text(hjust = 1, size = 10, face = "italic", color = "#666666"),
        plot.background = element_rect(fill = "#F5F5F5", color = NA),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "#E0E0E0", size = 0.5),
        panel.grid.minor = element_line(color = "#F2F2F2", size = 0.25),
        axis.title = element_text(size = 12, face = "bold", color = "#333333"),
        axis.text = element_text(size = 10, color = "#333333"),
        axis.ticks = element_line(color = "#D1D1D1")) +
  theme(legend.position = "none")

# Plot IncNodePurity
ggplot(importance_df, aes(x = reorder(Feature, IncNodePurity), y = IncNodePurity)) +
  geom_bar(stat = "identity", fill = "#8FC7A9", color = "#6F9F7A", size = 0.5) +
  coord_flip() +
  labs(title = "Feature Importance (IncNodePurity)",
       x = "Features", y = "Increase in Node Purity",
       caption = "Data source: Stock Market Data (NASDAQ, NYSE, S&P500)-MSFT") +
  theme_minimal(base_size = 14) +
  theme(plot.title = element_text(hjust = 0.5, color = "#1A1A1A", size = 16, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, color = "#4D4D4D", size = 14),
        plot.caption = element_text(hjust = 1, size = 10, face = "italic", color = "#666666"),
        plot.background = element_rect(fill = "#F5F5F5", color = NA),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "#E0E0E0", size = 0.5),
        panel.grid.minor = element_line(color = "#F2F2F2", size = 0.25),
        axis.title = element_text(size = 12, face = "bold", color = "#333333"),
        axis.text = element_text(size = 10, color = "#333333"),
        axis.ticks = element_line(color = "#D1D1D1")) +
  theme(legend.position = "none")



# Combining %IncMSE and IncNodePurity Plots
# Plot %IncMSE
plot_incMSE <- ggplot(importance_df, aes(x = reorder(Feature, `%IncMSE`), y = `%IncMSE`)) +
  geom_bar(stat = "identity", fill = "#6EC1E4", color = "#4A92B4", size = 0.5) +
  coord_flip() +
  labs(title = "Feature Importance (%IncMSE)",
       x = "Features", y = "% Increase in MSE",
       caption = "Data source: Stock Market Data (NASDAQ, NYSE, S&P500)-MSFT") +
  theme_minimal(base_size = 14) +
  theme(plot.title = element_text(hjust = 0.5, color = "#1A1A1A", size = 16, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, color = "#4D4D4D", size = 14),
        plot.caption = element_text(hjust = 1, size = 10, face = "italic", color = "#666666"),
        plot.background = element_rect(fill = "#F5F5F5", color = NA),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "#E0E0E0", size = 0.5),
        panel.grid.minor = element_line(color = "#F2F2F2", size = 0.25),
        axis.title = element_text(size = 12, face = "bold", color = "#333333"),
        axis.text = element_text(size = 10, color = "#333333"),
        axis.ticks = element_line(color = "#D1D1D1")) +
  theme(legend.position = "none")

# Plot IncNodePurity
plot_incNodePurity <- ggplot(importance_df, aes(x = reorder(Feature, IncNodePurity), y = IncNodePurity)) +
  geom_bar(stat = "identity", fill = "#8FC7A9", color = "#6F9F7A", size = 0.5) +
  coord_flip() +
  labs(title = "Feature Importance (IncNodePurity)",
       x = "Features", y = "Increase in Node Purity",
       caption = "Data source: Stock Market Data (NASDAQ, NYSE, S&P500)-MSFT") +
  theme_minimal(base_size = 14) +
  theme(plot.title = element_text(hjust = 0.5, color = "#1A1A1A", size = 16, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, color = "#4D4D4D", size = 14),
        plot.caption = element_text(hjust = 1, size = 10, face = "italic", color = "#666666"),
        plot.background = element_rect(fill = "#F5F5F5", color = NA),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color = "#E0E0E0", size = 0.5),
        panel.grid.minor = element_line(color = "#F2F2F2", size = 0.25),
        axis.title = element_text(size = 12, face = "bold", color = "#333333"),
        axis.text = element_text(size = 10, color = "#333333"),
        axis.ticks = element_line(color = "#D1D1D1")) +
  theme(legend.position = "none")

# Combine plots
grid.arrange(plot_incMSE, plot_incNodePurity, ncol = 1)



# =============================
# Step 10: Model Evaluation
# =============================
#  Predicting Closing Price Using the Random Forest Model
# Make predictions on the test data
rf_predictions <- predict(rf_model, newdata = test_data)

# Calculate performance metrics (MAE, RMSE, R²)
mae <- mean(abs(rf_predictions - test_data$Close)) # Calculate MAE
rmse <- sqrt(mean((rf_predictions - test_data$Close)^2)) # Calculate RMSE
r_squared <- 1 - sum((rf_predictions - test_data$Close)^2) / sum((mean(test_data$Close) - test_data$Close)^2) # Calculate R²

# Display performance metrics
cat("Random Forest Model Performance:\n")
cat("MAE:", mae, "\n")
cat("RMSE:", rmse, "\n")
cat("R²:", r_squared, "\n")


# =============================
# Step 11: Model Comparison
# =============================
# Model Comparison (Random Forest vs Linear Regression)
# Build and Evaluate the Linear Regression Model
# Train the Linear Regression model
lm_model <- lm(Close ~ Low + Open + Volume + High + SMA_10 + SMA_50 + DailyReturn, 
               data = train_data)

# Make predictions on the test data
lm_predictions <- predict(lm_model, newdata = test_data)

# Calculate performance metrics for Linear Regression
lm_mae <- mean(abs(lm_predictions - test_data$Close))
lm_rmse <- sqrt(mean((lm_predictions - test_data$Close)^2))
lm_r_squared <- 1 - sum((lm_predictions - test_data$Close)^2) / sum((mean(test_data$Close) - test_data$Close)^2)

# Display performance metrics
cat("Linear Regression Model Performance:\n")
cat("MAE:", lm_mae, "\n")
cat("RMSE:", lm_rmse, "\n")
cat("R²:", lm_r_squared, "\n")


# 5.2 Compare Predictions and Performance
# Compare Random Forest and Linear Regression predictions
comparison <- data.frame(
  Date = test_data$Date,
  Actual = test_data$Close,
  RF_Prediction = rf_predictions,
  LM_Prediction = lm_predictions
)

# Plot actual vs predicted closing price (Random Forest vs Linear Regression)
# High Quality Visualiation
ggplot(comparison, aes(x = Date)) +
  geom_line(aes(y = Actual, color = "Actual"), linewidth = 1) +  # Use 'linewidth' instead of 'size'
  geom_line(aes(y = RF_Prediction, color = "RF Prediction"), linewidth = 1, linetype = "dashed") +
  geom_line(aes(y = LM_Prediction, color = "LM Prediction"), linewidth = 1, linetype = "dotted") +
  labs(title = "Comparison of Actual vs Predicted Microsoft Closing Price", 
       subtitle = "Random Forest and Linear Regression Predictions", 
       caption = "Data source: Stock Market Data (NASDAQ, NYSE, S&P500)-MSFT") +
  scale_color_manual(values = c("Actual" = "black", "RF Prediction" = "blue", "LM Prediction" = "red")) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5, color = "#1A1A1A", size = 14, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, color = "#4D4D4D", size = 14),
    plot.caption = element_text(hjust = 1, size = 10, face = "italic", color = "#666666"),
    plot.background = element_rect(fill = "#F5F5F5", color = NA),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "#D3D3D3", size = 0.5),
    panel.grid.minor = element_line(color = "#E0E0E0", size = 0.25),
    axis.title = element_text(size = 12, face = "bold", color = "#333333"),
    axis.text = element_text(size = 10, color = "#333333"),
    axis.ticks = element_line(color = "#D1D1D1"),
    legend.position = "top",
    legend.title = element_text(face = "bold", color = "#333333"),
    legend.text = element_text(color = "#333333")
  ) +
  xlab("Date") + ylab("Closing Price (USD)")






# Actual Vs Predicted for Random Forest Model
# High-Quality Visualization for Random Forest Predictions
ggplot(comparison, aes(x = Date)) +
  geom_line(aes(y = Actual, color = "Actual"), linewidth = 1.5) +  
  geom_line(aes(y = RF_Prediction, color = "Random Forest Prediction"), linewidth = 1.5, linetype = "dashed", alpha = 0.8) +
  labs(title = "Actual vs Predicted Microsoft Closing Price", 
       subtitle = "Random Forest Model Predictions", 
       caption = "Data source: Stock Market Data (NASDAQ, NYSE, S&P500) - MSFT",
       x = "Date",
       y = "Closing Price (USD)") +
  scale_color_manual(values = c("Actual" = "red", "Random Forest Prediction" = "blue")) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5, color = "#1A1A1A", size = 16, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, color = "#4D4D4D", size = 14),
    plot.caption = element_text(hjust = 1, size = 10, face = "italic", color = "#666666"),
    plot.background = element_rect(fill = "#F5F5F5", color = NA),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "#D3D3D3", size = 0.5),
    panel.grid.minor = element_line(color = "#E0E0E0", size = 0.25),
    axis.title = element_text(size = 12, face = "bold", color = "#333333"),
    axis.text = element_text(size = 10, color = "#333333"),
    axis.ticks = element_line(color = "#D1D1D1"),
    legend.position = "top",
    legend.title = element_text(face = "bold", color = "#333333"),
    legend.text = element_text(color = "#333333")
  )


# Actual Vs Predicted for Linear Regression Model
# High-Quality Visualization for Linear Regression Predictions
ggplot(comparison, aes(x = Date)) +
  geom_line(aes(y = Actual, color = "Actual"), linewidth = 1.5) +  
  geom_line(aes(y = LM_Prediction, color = "Linear Regression Prediction"), 
            linewidth = 1.5, linetype = "dashed", alpha = 0.8) +
  labs(title = "Actual vs Predicted Microsoft Closing Price", 
       subtitle = "Linear Regression Model Predictions", 
       caption = "Data source: Stock Market Data (NASDAQ, NYSE, S&P500) - MSFT",
       x = "Date",
       y = "Closing Price (USD)") +
  scale_color_manual(values = c("Actual" = "red", "Linear Regression Prediction" = "blue")) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5, color = "#1A1A1A", size = 16, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, color = "#4D4D4D", size = 14),
    plot.caption = element_text(hjust = 1, size = 10, face = "italic", color = "#666666"),
    plot.background = element_rect(fill = "#F5F5F5", color = NA),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "#D3D3D3", size = 0.5),
    panel.grid.minor = element_line(color = "#E0E0E0", size = 0.25),
    axis.title = element_text(size = 12, face = "bold", color = "#333333"),
    axis.text = element_text(size = 10, color = "#333333"),
    axis.ticks = element_line(color = "#D1D1D1"),
    legend.position = "top",
    legend.title = element_text(face = "bold", color = "#333333"),
    legend.text = element_text(color = "#333333")
  )






# =============================
# Step 12: Recursive Feature Elimination (RFE)
# =============================
# This will help identify the most relevant predictors for Random Forest model.
# Define control using RFE
control <- rfeControl(functions = rfFuncs, method = "cv", number = 5)

# Run RFE
set.seed(42)  # Ensure reproducibility
rfe_result <- rfe(msft_data[, c("Low", "Open", "Volume", "High", "SMA_10", "SMA_50", "DailyReturn")], 
                  msft_data$Close, 
                  sizes = c(1:7), 
                  rfeControl = control)

# View results

print(rfe_result)
predictors(rfe_result)

# Plot variable importance
plot(rfe_result, type = c("g", "o"))


# High Quality Visualization
# Extract RFE results into a data frame
rfe_results_df <- data.frame(
  Variables = rfe_result$results$Variables,
  RMSE = rfe_result$results$RMSE,
  Rsquared = rfe_result$results$Rsquared,
  MAE = rfe_result$results$MAE
)

# Create the plot using ggplot2
ggplot(rfe_results_df, aes(x = Variables)) +
  geom_line(aes(y = RMSE, color = "RMSE"), size = 1.2) +
  geom_line(aes(y = Rsquared, color = "R²"), size = 1.2, linetype = "dashed") +
  geom_line(aes(y = MAE, color = "MAE"), size = 1.2, linetype = "dotted") +
  scale_color_manual(
    name = "Metrics",
    values = c("RMSE" = "#FF5733", "R²" = "#3375FF", "MAE" = "#33FF57")
  ) +
  labs(
    title = "Performance Metrics Across Subset Sizes",
    subtitle = "Recursive Feature Elimination Results",
    x = "Number of Variables",
    y = "Metric Value",
    caption = "Data Source: Stock Market Data (NASDAQ, NYSE, S&P500)-MSFT"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.background = element_rect(fill = "#F8F9FA", color = NA), # Light gray background
    panel.background = element_rect(fill = "#FFFFFF", color = "#D3D3D3"), # White panel with gray border
    panel.grid.major = element_line(color = "#E5E5E5"), # Soft gray gridlines
    panel.grid.minor = element_line(color = "#F0F0F0"), # Fainter minor gridlines
    plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, size = 16),
    plot.caption = element_text(size = 12, color = "gray"),
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 12),
    legend.position = "top",
    legend.title = element_text(face = "bold"),
    legend.text = element_text(size = 12)
  )


# =============================
# Step 13: Hyperparameter Tuning
# =============================
# Hyperparameter Tuning for Random Forest
# Define grid for tuning
rf_grid <- expand.grid(
  .mtry = c(2, 3, 4, 5),
  .splitrule = "variance",
  .min.node.size = c(1, 5, 10)
)

# Train Random Forest with grid search
set.seed(42)
rf_tuned <- train(
  Close ~ Low + Open + Volume + High + SMA_10 + SMA_50 + DailyReturn,
  data = train_data,
  method = "ranger",  # Efficient implementation of Random Forest
  trControl = trainControl(method = "cv", number = 5, verboseIter = TRUE),
  tuneGrid = rf_grid,
  importance = "impurity"
)

# View the best model parameters
print(rf_tuned$bestTune)






# =============================
# Step 14: Hyperparameter Tuning
# =============================
# Visualize residuals to check for patterns or bias.
# Residual Analysis for Random Forest
rf_residuals <- rf_predictions - test_data$Close

# Plot residuals
ggplot(data.frame(Date = test_data$Date, Residuals = rf_residuals), aes(x = Date, y = Residuals)) +
  geom_line(color = "red", size = 1.2) + # Thicker line for better visibility
  labs(title = "Residuals of Random Forest Predictions",
       x = "Date", y = "Residuals (Actual - Predicted)", 
       caption = "Data Source: Stock Market Data (NASDAQ, NYSE, S&P500)-MSFT") +
  theme_minimal(base_size = 15) + # Clean minimal theme with larger text
  theme(
    plot.title = element_text(face = "bold", size = 18, hjust = 0.5),  # Center and bold the title
    plot.caption = element_text(size = 10, face = "italic", hjust = 1),  # Style caption
    axis.title = element_text(size = 14),  # Larger axis titles
    axis.text = element_text(size = 12),   # Larger axis labels
    panel.grid.major = element_line(color = "grey90", size = 0.5),  # Light grid lines for a professional look
    panel.grid.minor = element_line(color = "grey95", size = 0.25), 
    panel.background = element_rect(fill = "white", color = "black", size = 0.5), # High-quality background
    plot.background = element_rect(fill = "white", color = NA)  # Clean overall background
  )

# =============================
# Step 15: Statistical Significance Testing
# =============================
# Test whether Random Forest outperforms Linear Regression using a paired t-test
# Calculate absolute errors
rf_errors <- abs(rf_predictions - test_data$Close)
lm_errors <- abs(lm_predictions - test_data$Close)

# Perform paired t-test
t_test_result <- t.test(rf_errors, lm_errors, paired = TRUE)

# Print results
print(t_test_result)

# Check the column names of the comparison data frame
colnames(comparison)


